apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-platform.gateway.name" . }}-service
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: {{ include "inference-platform.gateway.name" . }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
