{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-platform.gateway.service" . | quote }}
spec:
  type: {{ $.Values.gateway.service.type }}
  selector:
    app: {{ include "inference-platform.gateway.name" . | quote }}
  ports:
    - name: http
      port: {{ $.Values.gateway.service.port }}
      targetPort: {{ $.Values.gateway.service.targetPort }}
{{- end }}