{{- $models := include "inference-platform.discoveredModels" $ | fromYaml }}
{{- range $model := $models }}
{{- if $model.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-media-service-%s-service" (include "inference-platform.name" $) $model.name | quote }}
spec:
  type: {{ $.Values.mediaService.service.type }}
  selector:
    app: {{ printf "%s-media-service-%s-service" (include "inference-platform.name" $) $model.name | quote }}
  ports:
    - port: {{ $.Values.mediaService.service.port }}
      targetPort: {{ $.Values.mediaService.service.targetPort }}
---
{{- end }}
{{- end }}