model:
  id: aion
  name: AION

sizes:
  - id: aion-base
    name: AION Base

  - id: aion-large
    name: AION Large

data_types:
  - id: rgb-pil
    kind: image
    representation: pil_image

  - id: prediction-dict
    kind: dictionary

  - id: plot-prediction
    kind: image
    representation: matplotlib_figure

  - id: legacy-survey-dict
    kind: dictionary
    fields:
      - id: rgb
        data_type_id: rgb-pil

visualizers:
  - id: prediction-tensor-to-plot
    input:
      data_type_id: prediction-dict
    output:
      data_type_id: plot-prediction

datasets:
  - id: legacy-survey
    name: Legacy Survey
    path: "/mnt/home/vgoudal/aion-inference/datasets/MultimodalUniverse/legacysurvey/subset_1000"
    checkpoint_format: huggingface
    data_type_id: legacy-survey-dict

modalities:
  - id: rgb
    name: RGB Image
    data_type_id: rgb-pil

  - id: plot
    name: Plot
    data_type_id: plot-prediction

tasks:
  - id: redshift-prediction
    name: Redshift Prediction
    data_samples:
      modality_id: rgb
      multiple_data_selection: true
      display_name: true

    selected_data_samples:
      display: false

    data_outputs:
      modality_id: plot

    ui:
      text_top_screen: "Get redshift predictions for a set of images"
      data_size: { width: "200px", height: "200px" }
      submit_button_text: "Search Redshift Predictions"

  - id: similarity-search
    name: Similarity Search
    data_samples:
      modality_id: rgb

    selected_data_samples:
      display: true
      modality_id: rgb

    data_outputs:
      display_multiple_results: true
      modality_id: rgb

    ui:
      text_top_screen: "Find objects with similar photometry and morphology"
      data_size: { width: "120px", height: "120px" }
      selected_data_size: { width: "25vh", height: "25vh" }
      submit_button_text: "Search Similarity"