apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inference-platform.datasets.name" . }}
spec:
  resources:
    requests:
      storage: {{ .Values.storage.datasets.size | default "1Gi" }}
