apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inference-platform.mediaPvc.name" . }}
spec:
  accessModes:
    {{- range .Values.storage.mediaPvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.mediaPvc.size | quote }}
