apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inference-platform.models.name" . }}
spec:
  resources:
    requests:
      storage: {{ .Values.storage.models.size | default "1Gi" }}