model:
  id: resnet
  name: ResNet

sizes:
  - id: resnet18
    name: ResNet18

data_types:
  - id: tensor
    kind: tensor
    representation: torch_tensor
    shape: [C, H, W]

  - id: image
    kind: image
    representation: matplotlib_figure

  - id: subset-cifar10-dict
    kind: dictionary
    fields:
      - id: tensor
        data_type_id: tensor
      - id: image
        data_type_id: image

  - id: subset-cifar10-dict-list
    kind: list
    element_type:
      data_type_id: subset-cifar10-dict

datasets:
  - id: subset-cifar10
    name: Subset CIFAR-10
    path: "/mnt/home/vgoudal/polymathic-inference/resnet-cifar10-basics/data.pkl"
    checkpoint_format: pickle
    data_type_id: subset-cifar10-dict-list

modalities:
  - id: image
    name: RGB Image
    data_type_id: image

tasks:
  - id: image-similarity
    name: Image Similarity
    
    data_samples:
      modality_id: image

    data_outputs:
      modality_id: image

    ui:
      text_top_screen: "Select an image you want to find the most similar one"
      data_size: { width: "25vh", height: "25vh" }
      output_data_size: { width: "40vh", height: "35vh" }
      submit_button_text: "Search Most Similar Image"

    inference:
      input_data_type_id: tensor
      output_data_type_id: image