{{- if .Values.worker.enabled }}
{{- $models := include "inference-platform.discoveredModels" $ | fromYamlArray }}
{{- range $_, $model := $models }}
{{- if index $model "enabled" }}
{{- range $_, $size := (index $model "sizes") | default list }}
{{- if index $size "enabled" }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-platform.worker.name" (dict "root" $ "modelName" (index $model "name") "sizeName" (index $size "name")) | quote }}
spec:
  replicas: {{ index $size "replicas" | default 1 }}
  selector:
    matchLabels:
      app: {{ include "inference-platform.worker.name" (dict "root" $ "modelName" (index $model "name") "sizeName" (index $size "name")) | quote }}
  template:
    metadata:
      labels:
        app: {{ include "inference-platform.worker.name" (dict "root" $ "modelName" (index $model "name") "sizeName" (index $size "name")) | quote }}
    spec:
      containers:
        - name: worker
          image: "{{ $.Values.worker.image.repository }}:{{ index $model "name" }}"
          imagePullPolicy: {{ $.Values.worker.image.pullPolicy }}
          resources:
            requests:
              memory: {{ dig "resources" "requests" "memory" "1Gi" $size }}
              cpu: {{ dig "resources" "requests" "cpu" 1 $size }}
            limits:
              memory: {{ dig "resources" "limits" "memory" "1Gi" $size }}
              cpu: {{ dig "resources" "limits" "cpu" 2 $size }}
              {{- if index $size "enabled_gpu" }}
              nvidia.com/gpu: 1
              {{- end }}
          ports:
            - containerPort: {{ $.Values.worker.service.targetPort }}
          env:
            - name: MODEL_ID
              value: "{{ index $model "name" }}"
            - name: SIZE_ID
              value: "{{ index $size "name" }}"
            - name: WORKER_HOST
              value: {{ include "inference-platform.worker.service" (dict "root" $ "modelName" (index $model "name") "sizeName" (index $size "name")) | quote }}
            - name: WORKER_PORT
              value: {{ $.Values.worker.service.targetPort | toString | quote }}
            - name: MEDIA_SERVICE_HOST
              value: {{ include "inference-platform.media_service.service" (dict "root" $ "modelName" (index $model "name")) | quote }}
            - name: MEDIA_SERVICE_PORT
              value: {{ $.Values.mediaService.service.targetPort | toString | quote }}
          volumeMounts:
            - name: weights
              mountPath: {{ $.Values.storage.weights.mountPath | quote }}
            - name: datasets
              mountPath: {{ $.Values.storage.datasets.mountPath | quote }}
      volumes:
        - name: weights
          persistentVolumeClaim:
            claimName: {{ include "inference-platform.weights.name" $ }}
        - name: datasets
          persistentVolumeClaim:
            claimName: {{ include "inference-platform.datasets.name" $ }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
