{{- $models := include "inference-platform.discoveredModels" $ | fromYaml }}
{{- range $model := $models }}
{{- if $model.enabled }}
{{- range $size := $model.sizes }}
{{- if $size.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "inference-platform.worker.name" (dict "root" $ "modelName" $model.name "sizeName" $size.name)) | quote }}
spec:
  type: {{ $.Values.worker.service.type }}
  selector:
    app: {{ include "inference-platform.worker.name" (dict "root" $ "modelName" $model.name "sizeName" $size.name) | quote }}
  ports:
    - port: {{ $.Values.worker.service.port }}
      targetPort: {{ $.Values.worker.service.targetPort }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}