frontend:
  replicaCount: 1
  image:
    repository: frontend
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30007

gateway:
  replicaCount: 1
  image:
    repository: gateway
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

mediaService:
  image:
    repository: media-service
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 7000
    targetPort: 7000

worker:
  image:
    repository: worker
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 6000
    targetPort: 6000

storage:
  models:
    size: 1Gi
    mountPath: /data/models

  datasets:
    size: 1Gi
    mountPath: /data/datasets

  mediaFiles:
    size: 1Gi
    mountPath: /data/media_files

  weights:
    size: 1Gi
    mountPath: /data/weights