frontend:
  image:
    pullPolicy: Never
    repository: frontend
    tag: latest
  replicaCount: 1
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  service:
    nodePort: 30007
    port: 80
    targetPort: 80
    type: NodePort
gateway:
  image:
    pullPolicy: Never
    repository: gateway
    tag: latest
  replicaCount: 1
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  service:
    port: 8000
    targetPort: 8000
    type: ClusterIP
mediaService:
  image:
    pullPolicy: Never
    repository: media-service
  resources:
    limits:
      cpu: 8
      memory: 8Gi
    requests:
      cpu: 1
      memory: 1Gi
  service:
    port: 7000
    targetPort: 7000
    type: ClusterIP
storage:
  datasets:
    accessModes:
    - ReadOnlyMany
    mountPath: /data/datasets
    size: 9Gi
  mediaFiles:
    accessModes:
    - ReadWriteMany
    mountPath: /data/media_files
    size: 2Gi
  weights:
    accessModes:
    - ReadOnlyMany
    mountPath: /data/weights
    size: 6Gi
timeSlicing:
  replicas: 4
worker:
  image:
    pullPolicy: Never
    repository: worker
  service:
    port: 6000
    targetPort: 6000
    type: ClusterIP
