model:
  id: sol
  name: SOL

sizes:
  - id: sol-base
    name: SOL Base
    path: "/mnt/home/vgoudal/ceph/huggingface/models/polymathic-ai/aion-base"
    resources:
      requests:
        memory: 8Gi
        cpu: 4
      limits:
        memory: 9Gi
        cpu: 4

data_types:
  - id: x_tensor
    kind: tensor
    representation: torch_tensor
    shape: [C, F, H, W]

  - id: x_video
    kind: video
    representation: matplotlib_animation
    fps: 7

  - id: sol_dataset_dict_formatted
    kind: dictionary
    fields:
      - id: x_obs
        data_type_id: x_tensor

  - id: sol_dataset_dict_list
    kind: list

  - id: sol_dataset_dict_list_formatted
    kind: list
    element_type:
      data_type_id: sol_dataset_dict_formatted

visualizers:
  - id: video_maker
    function_name: make_video
    input_data_type_id: x_tensor
    output_data_type_id: x_video
    output_modalities: [br, bp, bt, dopplergram, continuum, aia_1700, aia_1600, aia_0335, aia_0304, aia_0211, aia_0193, aia_0171, aia_0131, aia_0094]

dataset_formatters:
  - id: sol_dataset_formatter
    function_name: format_sol_dataset
    output_data_type_id: sol_dataset_dict_list_formatted

datasets:
  - id: sol_dataset
    name: SOL Dataset
    path: /mnt/home/vgoudal/polymathic-inference/aion-inference/datasets/sol/dataset.pt
    checkpoint_format: torch_pt
    dataset_formatter_id: sol_dataset_formatter

modalities:
  - id: br
    name: BR
    data_type_id: x_video

  - id: bp
    name: BP
    data_type_id: x_video

  - id: bt
    name: BT
    data_type_id: x_video

  - id: dopplergram
    name: Dopplergram
    data_type_id: x_video

  - id: continuum
    name: Continuum
    data_type_id: x_video

  - id: aia_1700
    name: AIA 1700
    data_type_id: x_video

  - id: aia_1600
    name: AIA 1600
    data_type_id: x_video

  - id: aia_0335
    name: AIA 0335
    data_type_id: x_video

  - id: aia_0304
    name: AIA 0304
    data_type_id: x_video

  - id: aia_0211
    name: AIA 0211
    data_type_id: x_video

  - id: aia_0193
    name: AIA 0193
    data_type_id: x_video

  - id: aia_0171
    name: AIA 0171
    data_type_id: x_video

  - id: aia_0131
    name: AIA 0131
    data_type_id: x_video

  - id: aia_0094
    name: AIA 0094
    data_type_id: x_video

tasks:
  - id: sun-prediction
    name: Sun Prediction

    data_samples:
      modality_id: aia_0304
      sample_size: 10

    selected_data_samples:
      display: true
      display_modalities_names: true
      display_multiple_modalities_simultaneously: true
      modality_ids: [bt, aia_1700, aia_0304]

    data_outputs:
      display: true
      display_modalities_names: true
      display_multiple_modalities_simultaneously: true
      modality_ids: [bt, aia_1700, aia_0304]
      enable_switch_modalities: true
      switch_modality_ids: [bt, aia_1700, aia_0304, aia_0193, aia_0094]

    ui:
      text_top_screen: "Predict the sun's activity for a given video"
      data_size: { width: "120px", height: "120px" }
      selected_data_size: { width: "20vh", height: "20vh" }
      output_data_size: { width: "20vh", height: "20vh" }
      submit_button_text: "Predict Sun Activity"

    inference:
      input_data_type_id: sol_dataset_dict_formatted
      output_data_type_id: x_tensor

information:
  extended_name: "SOL: Solar Orbiter Localization"
  description: "Deep learning is everywhere in astronomy, but most models live in silos—built for one data type, one survey, and one bespoke task. As a result, they must be retrained whenever these settings change. The AstronomIcal Omnimodal Network (AION-1) changes this: a single foundation model that spans multiple surveys and data types, producing a unified representation that transfers across domains and performs strongly even in low-data regimes. By learning shared astrophysical structure across instruments and modalities, AION-1 not only removes the need for retraining—it enables better performance, faster adaptation, and a deeper physical understanding from fewer examples."
  authors: "Liam Parker, Francois Lanusse, Jeff Shen, Ollie Liu, Tom Hehir, Leopoldo Sarra, Lucas Meyer, Micah Bowles, Sebastian Wagner-Carena, Helen Qu, Siavash Golkar, Alberto Bietti, Hatim Bourfoune, Nathan Casserau, Pierre Cornette, Keiya Hirashima, Geraud Krawezik, Ruben Ohana, Nicholas Lourie, Michael McCabe, Rudy Morel, Payel Mukhopadhyay, Mariel Pettee, Bruno Regaldo-Saint Blancard, Kyunghyun Cho, Miles Cranmer, Shirley Ho"
  links:
    - name: "Github"
      url: "https://github.com/PolymathicAI/AION"
      alt: "SOL API and Code"
    - name: "Blog"
      url: "https://polymathic-ai.org/blog/aion-1/"
      alt: "SOL"
    - name: "Paper"
      url: "https://arxiv.org/abs/2510.17960"
      alt: "SOL: Solar Orbiter Localization"
    - name: "Model Weights"
      url: "https://huggingface.co/polymathic-ai/aion-base"
      alt: "SOL Hugging Face"
    - name: "Tutorial"
      url: "https://colab.research.google.com/github/PolymathicAI/AION/blob/main/notebooks/Tutorial.ipynb"
      alt: "SOL quick start"