model:
  id: sol
  name: SOL

sizes:
  - id: sol-base
    name: SOL Base

  - id: sol-large
    name: SOL Large

  - id: sol-xlarge
    name: SOL XLarge

media-types:
  - id: video
    type: video
    python-frame-format: matplotlib.animation.FuncAnimation
    fps: 25

modalities:
  - id: br
    name: BR
    media-type-id: video

  - id: bp
    name: BP
    media-type-id: video

  - id: bt
    name: BT
    media-type-id: video

  - id: dopplergram
    name: Dopplergram
    media-type-id: video

  - id: continuum
    name: Continuum
    media-type-id: video

  - id: aia_1700
    name: AIA 1700
    media-type-id: video

  - id: aia_1600
    name: AIA 1600
    media-type-id: video

  - id: aia_0335
    name: AIA 0335
    media-type-id: video

  - id: aia_0304
    name: AIA 0304
    media-type-id: video

  - id: aia_0211
    name: AIA 0211
    media-type-id: video

  - id: aia_0193
    name: AIA 0193
    media-type-id: video

  - id: aia_0171
    name: AIA 0171
    media-type-id: video

  - id: aia_0131
    name: AIA 0131
    media-type-id: video

  - id: aia_0094
    name: AIA 0094
    media-type-id: video

  - id: gong_6768
    name: GONG 6768
    media-type-id: video

tasks:
  - id: sun-prediction
    name: Sun Prediction
    data-samples:
      modality-id: br
      multiple-data-selection: false
      display-name: true

    selected-data-samples:
      display-name: false
      display: false
      display-multiple-modalities: true
      modality-ids: [br, bp, bt]
      switch-modalities:
        enabled: false

    data-outputs:
      display-name: false
      display-multiple-results: false
      display-multiple-modalities: true
      modality-ids: [br, bp, bt]
      switch-modalities:
        enabled: true
        modality-ids: [br, bp, bt]

    ui:
      text-top-screen: "Predict the sun's activity for a given video"
      data-size: { width: "120px", height: "120px" }
      selected-data-size: { width: "25vh", height: "25vh" }
      submit-button-text: "Predict Sun Activity"