{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-platform.frontend.name" . }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "inference-platform.frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "inference-platform.frontend.name" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          resources:
            requests:
              memory: "{{ .Values.frontend.resources.requests.memory }}"
              cpu: "{{ .Values.frontend.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.frontend.resources.limits.memory }}"
              cpu: "{{ .Values.frontend.resources.limits.cpu }}"
          env:
            - name: GATEWAY_SERVICE_HOST
              value: {{ include "inference-platform.gateway.service" . | quote }}
            - name: GATEWAY_SERVICE_PORT
              value: {{ .Values.gateway.service.targetPort | toString | quote }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
{{- end }}