apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-platform.frontend.name" . }}-service
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "inference-platform.frontend.name" . }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}