apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:latest
          env:
            - name: MEDIA_FILES_PATH
              value: "/media_files"
            - name: GATEWAY_PORT
              value: "8000"
            - name: GATEWAY_HOST
              value: "localhost"
          volumeMounts:
            - name: media-volume
              mountPath: /media_files
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-files-pvc